version: '3'
services:
  natour-app:
    container_name: natour
    restart: always
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    container_name: natour-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
